// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AIArtifact struct {
	ID                string              `json:"id"`
	ArtifactType      string              `json:"artifactType"`
	Owner             *OwnerReference     `json:"owner"`
	Title             string              `json:"title"`
	SourceInputs      string              `json:"sourceInputs"`
	GeneratedContent  string              `json:"generatedContent"`
	UserEditedContent *string             `json:"userEditedContent,omitempty"`
	CurrentContent    string              `json:"currentContent"`
	Status            string              `json:"status"`
	Sensitive         bool                `json:"sensitive"`
	SupersededBy      *string             `json:"supersededBy,omitempty"`
	Provenance        *ArtifactProvenance `json:"provenance"`
	CreatedAt         string              `json:"createdAt"`
	UpdatedAt         string              `json:"updatedAt"`
}

type AddApplicationNoteInput struct {
	ApplicationID string `json:"applicationId"`
	Body          string `json:"body"`
}

type AdvanceApplicationStageInput struct {
	ApplicationID string `json:"applicationId"`
	ToStage       string `json:"toStage"`
}

type ApplicationNote struct {
	ID        string `json:"id"`
	Body      string `json:"body"`
	CreatedAt string `json:"createdAt"`
}

type ArtifactProvenance struct {
	ProviderName  *string `json:"providerName,omitempty"`
	ModelName     *string `json:"modelName,omitempty"`
	PromptID      *string `json:"promptId,omitempty"`
	UsageMetadata string  `json:"usageMetadata"`
	RawProviderID *string `json:"rawProviderId,omitempty"`
}

type CandidateGroundingContext struct {
	Profile *CandidateProfile        `json:"profile"`
	Memory  []*CandidateMemoryRecord `json:"memory"`
}

type CandidateMemoryRecord struct {
	ID           string  `json:"id"`
	MemoryType   string  `json:"memoryType"`
	Title        string  `json:"title"`
	Body         string  `json:"body"`
	Source       string  `json:"source"`
	Approved     bool    `json:"approved"`
	Sensitive    bool    `json:"sensitive"`
	ArchivedAt   *string `json:"archivedAt,omitempty"`
	SupersededBy *string `json:"supersededBy,omitempty"`
	Metadata     string  `json:"metadata"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}

type CandidateProfile struct {
	ID                       string `json:"id"`
	TargetRoles              string `json:"targetRoles"`
	PreferredStack           string `json:"preferredStack"`
	CompensationExpectations string `json:"compensationExpectations"`
	LocationPreferences      string `json:"locationPreferences"`
	WorkConstraints          string `json:"workConstraints"`
	CompanyPreferences       string `json:"companyPreferences"`
	WritingTone              string `json:"writingTone"`
	PositioningSummary       string `json:"positioningSummary"`
	CreatedAt                string `json:"createdAt"`
	UpdatedAt                string `json:"updatedAt"`
}

type CompleteFollowUpReminderInput struct {
	ApplicationID string `json:"applicationId"`
	ReminderID    string `json:"reminderId"`
}

type CreateAIArtifactInput struct {
	ArtifactType      string  `json:"artifactType"`
	OwnerType         string  `json:"ownerType"`
	OwnerID           string  `json:"ownerId"`
	Title             string  `json:"title"`
	SourceInputs      string  `json:"sourceInputs"`
	GeneratedContent  string  `json:"generatedContent"`
	UserEditedContent *string `json:"userEditedContent,omitempty"`
	Status            string  `json:"status"`
	Sensitive         bool    `json:"sensitive"`
	ProviderName      *string `json:"providerName,omitempty"`
	ModelName         *string `json:"modelName,omitempty"`
	PromptID          *string `json:"promptId,omitempty"`
	UsageMetadata     string  `json:"usageMetadata"`
	RawProviderID     *string `json:"rawProviderId,omitempty"`
}

type CreateCandidateMemoryRecordInput struct {
	MemoryType string `json:"memoryType"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Source     string `json:"source"`
	Approved   bool   `json:"approved"`
	Sensitive  bool   `json:"sensitive"`
	Metadata   string `json:"metadata"`
}

type CreateFollowUpReminderInput struct {
	ApplicationID string `json:"applicationId"`
	DueAt         string `json:"dueAt"`
	Note          string `json:"note"`
}

type CreateSavedOpportunityInput struct {
	Company        string `json:"company"`
	RoleTitle      string `json:"roleTitle"`
	PostingURL     string `json:"postingUrl"`
	Source         string `json:"source"`
	Location       string `json:"location"`
	Compensation   string `json:"compensation"`
	EmploymentType string `json:"employmentType"`
}

type FollowUpReminder struct {
	ID            string  `json:"id"`
	ApplicationID string  `json:"applicationId"`
	DueAt         string  `json:"dueAt"`
	Note          string  `json:"note"`
	CompletedAt   *string `json:"completedAt,omitempty"`
}

type Interview struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	ScheduledAt string `json:"scheduledAt"`
	Notes       string `json:"notes"`
	Outcome     string `json:"outcome"`
}

type JobApplication struct {
	ID             string              `json:"id"`
	Company        string              `json:"company"`
	RoleTitle      string              `json:"roleTitle"`
	PostingURL     string              `json:"postingUrl"`
	Source         string              `json:"source"`
	Location       string              `json:"location"`
	Compensation   string              `json:"compensation"`
	EmploymentType string              `json:"employmentType"`
	Stage          string              `json:"stage"`
	Timeline       []*TimelineEvent    `json:"timeline"`
	Interviews     []*Interview        `json:"interviews"`
	FollowUps      []*FollowUpReminder `json:"followUps"`
	Notes          []*ApplicationNote  `json:"notes"`
}

type Mutation struct {
}

type OwnerReference struct {
	Type string `json:"type"`
	ID   string `json:"id"`
}

type Query struct {
}

type RecordInterviewOutcomeInput struct {
	ApplicationID string `json:"applicationId"`
	InterviewID   string `json:"interviewId"`
	Outcome       string `json:"outcome"`
}

type ScheduleInterviewInput struct {
	ApplicationID string `json:"applicationId"`
	Type          string `json:"type"`
	ScheduledAt   string `json:"scheduledAt"`
	Notes         string `json:"notes"`
}

type TimelineEvent struct {
	ID          string `json:"id"`
	OccurredAt  string `json:"occurredAt"`
	Description string `json:"description"`
}

type UpdateCandidateMemoryRecordInput struct {
	ID         string `json:"id"`
	MemoryType string `json:"memoryType"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Source     string `json:"source"`
	Approved   bool   `json:"approved"`
	Sensitive  bool   `json:"sensitive"`
	Metadata   string `json:"metadata"`
}

type UpdateCandidateProfileInput struct {
	TargetRoles              string `json:"targetRoles"`
	PreferredStack           string `json:"preferredStack"`
	CompensationExpectations string `json:"compensationExpectations"`
	LocationPreferences      string `json:"locationPreferences"`
	WorkConstraints          string `json:"workConstraints"`
	CompanyPreferences       string `json:"companyPreferences"`
	WritingTone              string `json:"writingTone"`
	PositioningSummary       string `json:"positioningSummary"`
}

type ApplicationStage string

const (
	ApplicationStageSaved              ApplicationStage = "Saved"
	ApplicationStageApplied            ApplicationStage = "Applied"
	ApplicationStageScreening          ApplicationStage = "Screening"
	ApplicationStageTechnicalInterview ApplicationStage = "TechnicalInterview"
	ApplicationStageOnsite             ApplicationStage = "Onsite"
	ApplicationStageOffer              ApplicationStage = "Offer"
	ApplicationStageRejected           ApplicationStage = "Rejected"
	ApplicationStageWithdrawn          ApplicationStage = "Withdrawn"
)

var AllApplicationStage = []ApplicationStage{
	ApplicationStageSaved,
	ApplicationStageApplied,
	ApplicationStageScreening,
	ApplicationStageTechnicalInterview,
	ApplicationStageOnsite,
	ApplicationStageOffer,
	ApplicationStageRejected,
	ApplicationStageWithdrawn,
}

func (e ApplicationStage) IsValid() bool {
	switch e {
	case ApplicationStageSaved, ApplicationStageApplied, ApplicationStageScreening, ApplicationStageTechnicalInterview, ApplicationStageOnsite, ApplicationStageOffer, ApplicationStageRejected, ApplicationStageWithdrawn:
		return true
	}
	return false
}

func (e ApplicationStage) String() string {
	return string(e)
}

func (e *ApplicationStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApplicationStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApplicationStage", str)
	}
	return nil
}

func (e ApplicationStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApplicationStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApplicationStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EmploymentType string

const (
	EmploymentTypeFullTime   EmploymentType = "FullTime"
	EmploymentTypeContract   EmploymentType = "Contract"
	EmploymentTypePartTime   EmploymentType = "PartTime"
	EmploymentTypeInternship EmploymentType = "Internship"
	EmploymentTypeOther      EmploymentType = "Other"
)

var AllEmploymentType = []EmploymentType{
	EmploymentTypeFullTime,
	EmploymentTypeContract,
	EmploymentTypePartTime,
	EmploymentTypeInternship,
	EmploymentTypeOther,
}

func (e EmploymentType) IsValid() bool {
	switch e {
	case EmploymentTypeFullTime, EmploymentTypeContract, EmploymentTypePartTime, EmploymentTypeInternship, EmploymentTypeOther:
		return true
	}
	return false
}

func (e EmploymentType) String() string {
	return string(e)
}

func (e *EmploymentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmploymentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmploymentType", str)
	}
	return nil
}

func (e EmploymentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EmploymentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EmploymentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InterviewOutcome string

const (
	InterviewOutcomeScheduled  InterviewOutcome = "Scheduled"
	InterviewOutcomePassed     InterviewOutcome = "Passed"
	InterviewOutcomeRejected   InterviewOutcome = "Rejected"
	InterviewOutcomeNoDecision InterviewOutcome = "NoDecision"
)

var AllInterviewOutcome = []InterviewOutcome{
	InterviewOutcomeScheduled,
	InterviewOutcomePassed,
	InterviewOutcomeRejected,
	InterviewOutcomeNoDecision,
}

func (e InterviewOutcome) IsValid() bool {
	switch e {
	case InterviewOutcomeScheduled, InterviewOutcomePassed, InterviewOutcomeRejected, InterviewOutcomeNoDecision:
		return true
	}
	return false
}

func (e InterviewOutcome) String() string {
	return string(e)
}

func (e *InterviewOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterviewOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterviewOutcome", str)
	}
	return nil
}

func (e InterviewOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterviewOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterviewOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InterviewType string

const (
	InterviewTypeRecruiterScreen InterviewType = "RecruiterScreen"
	InterviewTypeHiringManager   InterviewType = "HiringManager"
	InterviewTypeTechnical       InterviewType = "Technical"
	InterviewTypeOnsite          InterviewType = "Onsite"
	InterviewTypeOther           InterviewType = "Other"
)

var AllInterviewType = []InterviewType{
	InterviewTypeRecruiterScreen,
	InterviewTypeHiringManager,
	InterviewTypeTechnical,
	InterviewTypeOnsite,
	InterviewTypeOther,
}

func (e InterviewType) IsValid() bool {
	switch e {
	case InterviewTypeRecruiterScreen, InterviewTypeHiringManager, InterviewTypeTechnical, InterviewTypeOnsite, InterviewTypeOther:
		return true
	}
	return false
}

func (e InterviewType) String() string {
	return string(e)
}

func (e *InterviewType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterviewType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterviewType", str)
	}
	return nil
}

func (e InterviewType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterviewType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterviewType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobSource string

const (
	JobSourceLinkedIn    JobSource = "LinkedIn"
	JobSourceReferral    JobSource = "Referral"
	JobSourceRecruiter   JobSource = "Recruiter"
	JobSourceCompanySite JobSource = "CompanySite"
	JobSourceOther       JobSource = "Other"
)

var AllJobSource = []JobSource{
	JobSourceLinkedIn,
	JobSourceReferral,
	JobSourceRecruiter,
	JobSourceCompanySite,
	JobSourceOther,
}

func (e JobSource) IsValid() bool {
	switch e {
	case JobSourceLinkedIn, JobSourceReferral, JobSourceRecruiter, JobSourceCompanySite, JobSourceOther:
		return true
	}
	return false
}

func (e JobSource) String() string {
	return string(e)
}

func (e *JobSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobSource", str)
	}
	return nil
}

func (e JobSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
