// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_artifacts.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getAIArtifact = `-- name: GetAIArtifact :one
SELECT id, artifact_type, owner_type, owner_id, title, source_inputs,
       generated_content, user_edited_content, status, sensitive, superseded_by,
       provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
       created_at, updated_at
FROM ai_artifacts
WHERE id = $1
`

func (q *Queries) GetAIArtifact(ctx context.Context, id string) (AiArtifact, error) {
	row := q.db.QueryRowContext(ctx, getAIArtifact, id)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.OwnerType,
		&i.OwnerID,
		&i.Title,
		&i.SourceInputs,
		&i.GeneratedContent,
		&i.UserEditedContent,
		&i.Status,
		&i.Sensitive,
		&i.SupersededBy,
		&i.ProviderName,
		&i.ModelName,
		&i.PromptID,
		&i.UsageMetadata,
		&i.RawProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAIArtifact = `-- name: InsertAIArtifact :one
INSERT INTO ai_artifacts (
    id, artifact_type, owner_type, owner_id, title, source_inputs,
    generated_content, user_edited_content, status, sensitive, superseded_by,
    provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, artifact_type, owner_type, owner_id, title, source_inputs,
          generated_content, user_edited_content, status, sensitive, superseded_by,
          provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
          created_at, updated_at
`

type InsertAIArtifactParams struct {
	ID                string
	ArtifactType      string
	OwnerType         string
	OwnerID           string
	Title             string
	SourceInputs      json.RawMessage
	GeneratedContent  string
	UserEditedContent sql.NullString
	Status            string
	Sensitive         bool
	SupersededBy      sql.NullString
	ProviderName      sql.NullString
	ModelName         sql.NullString
	PromptID          sql.NullString
	UsageMetadata     json.RawMessage
	RawProviderID     sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) InsertAIArtifact(ctx context.Context, arg InsertAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRowContext(ctx, insertAIArtifact,
		arg.ID,
		arg.ArtifactType,
		arg.OwnerType,
		arg.OwnerID,
		arg.Title,
		arg.SourceInputs,
		arg.GeneratedContent,
		arg.UserEditedContent,
		arg.Status,
		arg.Sensitive,
		arg.SupersededBy,
		arg.ProviderName,
		arg.ModelName,
		arg.PromptID,
		arg.UsageMetadata,
		arg.RawProviderID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.OwnerType,
		&i.OwnerID,
		&i.Title,
		&i.SourceInputs,
		&i.GeneratedContent,
		&i.UserEditedContent,
		&i.Status,
		&i.Sensitive,
		&i.SupersededBy,
		&i.ProviderName,
		&i.ModelName,
		&i.PromptID,
		&i.UsageMetadata,
		&i.RawProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIArtifactsByOwner = `-- name: ListAIArtifactsByOwner :many
SELECT id, artifact_type, owner_type, owner_id, title, source_inputs,
       generated_content, user_edited_content, status, sensitive, superseded_by,
       provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
       created_at, updated_at
FROM ai_artifacts
WHERE owner_type = $1 AND owner_id = $2
ORDER BY created_at DESC
`

type ListAIArtifactsByOwnerParams struct {
	OwnerType string
	OwnerID   string
}

func (q *Queries) ListAIArtifactsByOwner(ctx context.Context, arg ListAIArtifactsByOwnerParams) ([]AiArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listAIArtifactsByOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiArtifact
	for rows.Next() {
		var i AiArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactType,
			&i.OwnerType,
			&i.OwnerID,
			&i.Title,
			&i.SourceInputs,
			&i.GeneratedContent,
			&i.UserEditedContent,
			&i.Status,
			&i.Sensitive,
			&i.SupersededBy,
			&i.ProviderName,
			&i.ModelName,
			&i.PromptID,
			&i.UsageMetadata,
			&i.RawProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeAIArtifact = `-- name: SupersedeAIArtifact :one
UPDATE ai_artifacts
SET status = 'Superseded',
    superseded_by = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, artifact_type, owner_type, owner_id, title, source_inputs,
          generated_content, user_edited_content, status, sensitive, superseded_by,
          provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
          created_at, updated_at
`

type SupersedeAIArtifactParams struct {
	ID           string
	SupersededBy sql.NullString
	UpdatedAt    time.Time
}

func (q *Queries) SupersedeAIArtifact(ctx context.Context, arg SupersedeAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRowContext(ctx, supersedeAIArtifact, arg.ID, arg.SupersededBy, arg.UpdatedAt)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.OwnerType,
		&i.OwnerID,
		&i.Title,
		&i.SourceInputs,
		&i.GeneratedContent,
		&i.UserEditedContent,
		&i.Status,
		&i.Sensitive,
		&i.SupersededBy,
		&i.ProviderName,
		&i.ModelName,
		&i.PromptID,
		&i.UsageMetadata,
		&i.RawProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAIArtifactEditedContent = `-- name: UpdateAIArtifactEditedContent :one
UPDATE ai_artifacts
SET user_edited_content = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, artifact_type, owner_type, owner_id, title, source_inputs,
          generated_content, user_edited_content, status, sensitive, superseded_by,
          provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
          created_at, updated_at
`

type UpdateAIArtifactEditedContentParams struct {
	ID                string
	UserEditedContent sql.NullString
	UpdatedAt         time.Time
}

func (q *Queries) UpdateAIArtifactEditedContent(ctx context.Context, arg UpdateAIArtifactEditedContentParams) (AiArtifact, error) {
	row := q.db.QueryRowContext(ctx, updateAIArtifactEditedContent, arg.ID, arg.UserEditedContent, arg.UpdatedAt)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.OwnerType,
		&i.OwnerID,
		&i.Title,
		&i.SourceInputs,
		&i.GeneratedContent,
		&i.UserEditedContent,
		&i.Status,
		&i.Sensitive,
		&i.SupersededBy,
		&i.ProviderName,
		&i.ModelName,
		&i.PromptID,
		&i.UsageMetadata,
		&i.RawProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAIArtifactStatus = `-- name: UpdateAIArtifactStatus :one
UPDATE ai_artifacts
SET status = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, artifact_type, owner_type, owner_id, title, source_inputs,
          generated_content, user_edited_content, status, sensitive, superseded_by,
          provider_name, model_name, prompt_id, usage_metadata, raw_provider_id,
          created_at, updated_at
`

type UpdateAIArtifactStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateAIArtifactStatus(ctx context.Context, arg UpdateAIArtifactStatusParams) (AiArtifact, error) {
	row := q.db.QueryRowContext(ctx, updateAIArtifactStatus, arg.ID, arg.Status, arg.UpdatedAt)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.OwnerType,
		&i.OwnerID,
		&i.Title,
		&i.SourceInputs,
		&i.GeneratedContent,
		&i.UserEditedContent,
		&i.Status,
		&i.Sensitive,
		&i.SupersededBy,
		&i.ProviderName,
		&i.ModelName,
		&i.PromptID,
		&i.UsageMetadata,
		&i.RawProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
