// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidate_memory_records.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const archiveCandidateMemoryRecord = `-- name: ArchiveCandidateMemoryRecord :one
UPDATE candidate_memory_records
SET archived_at = $2,
    updated_at = $2
WHERE id = $1
RETURNING id, memory_type, title, body, source, approved, sensitive,
          archived_at, superseded_by, metadata, created_at, updated_at
`

type ArchiveCandidateMemoryRecordParams struct {
	ID         string
	ArchivedAt *time.Time
}

func (q *Queries) ArchiveCandidateMemoryRecord(ctx context.Context, arg ArchiveCandidateMemoryRecordParams) (CandidateMemoryRecord, error) {
	row := q.db.QueryRowContext(ctx, archiveCandidateMemoryRecord, arg.ID, arg.ArchivedAt)
	var i CandidateMemoryRecord
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Approved,
		&i.Sensitive,
		&i.ArchivedAt,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateMemoryRecord = `-- name: GetCandidateMemoryRecord :one
SELECT id, memory_type, title, body, source, approved, sensitive,
       archived_at, superseded_by, metadata, created_at, updated_at
FROM candidate_memory_records
WHERE id = $1
`

func (q *Queries) GetCandidateMemoryRecord(ctx context.Context, id string) (CandidateMemoryRecord, error) {
	row := q.db.QueryRowContext(ctx, getCandidateMemoryRecord, id)
	var i CandidateMemoryRecord
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Approved,
		&i.Sensitive,
		&i.ArchivedAt,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCandidateMemoryRecord = `-- name: InsertCandidateMemoryRecord :one
INSERT INTO candidate_memory_records (
    id, memory_type, title, body, source, approved, sensitive,
    archived_at, superseded_by, metadata, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, memory_type, title, body, source, approved, sensitive,
          archived_at, superseded_by, metadata, created_at, updated_at
`

type InsertCandidateMemoryRecordParams struct {
	ID           string
	MemoryType   string
	Title        string
	Body         string
	Source       string
	Approved     bool
	Sensitive    bool
	ArchivedAt   *time.Time
	SupersededBy sql.NullString
	Metadata     json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) InsertCandidateMemoryRecord(ctx context.Context, arg InsertCandidateMemoryRecordParams) (CandidateMemoryRecord, error) {
	row := q.db.QueryRowContext(ctx, insertCandidateMemoryRecord,
		arg.ID,
		arg.MemoryType,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Approved,
		arg.Sensitive,
		arg.ArchivedAt,
		arg.SupersededBy,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CandidateMemoryRecord
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Approved,
		&i.Sensitive,
		&i.ArchivedAt,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedCurrentCandidateMemoryRecords = `-- name: ListApprovedCurrentCandidateMemoryRecords :many
SELECT id, memory_type, title, body, source, approved, sensitive,
       archived_at, superseded_by, metadata, created_at, updated_at
FROM candidate_memory_records
WHERE approved = TRUE AND archived_at IS NULL AND superseded_by IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListApprovedCurrentCandidateMemoryRecords(ctx context.Context) ([]CandidateMemoryRecord, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedCurrentCandidateMemoryRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateMemoryRecord
	for rows.Next() {
		var i CandidateMemoryRecord
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.Approved,
			&i.Sensitive,
			&i.ArchivedAt,
			&i.SupersededBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidateMemoryRecords = `-- name: ListCandidateMemoryRecords :many
SELECT id, memory_type, title, body, source, approved, sensitive,
       archived_at, superseded_by, metadata, created_at, updated_at
FROM candidate_memory_records
ORDER BY (archived_at IS NULL AND superseded_by IS NULL) DESC, created_at DESC
`

func (q *Queries) ListCandidateMemoryRecords(ctx context.Context) ([]CandidateMemoryRecord, error) {
	rows, err := q.db.QueryContext(ctx, listCandidateMemoryRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateMemoryRecord
	for rows.Next() {
		var i CandidateMemoryRecord
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.Approved,
			&i.Sensitive,
			&i.ArchivedAt,
			&i.SupersededBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeCandidateMemoryRecord = `-- name: SupersedeCandidateMemoryRecord :one
UPDATE candidate_memory_records
SET superseded_by = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, memory_type, title, body, source, approved, sensitive,
          archived_at, superseded_by, metadata, created_at, updated_at
`

type SupersedeCandidateMemoryRecordParams struct {
	ID           string
	SupersededBy sql.NullString
	UpdatedAt    time.Time
}

func (q *Queries) SupersedeCandidateMemoryRecord(ctx context.Context, arg SupersedeCandidateMemoryRecordParams) (CandidateMemoryRecord, error) {
	row := q.db.QueryRowContext(ctx, supersedeCandidateMemoryRecord, arg.ID, arg.SupersededBy, arg.UpdatedAt)
	var i CandidateMemoryRecord
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Approved,
		&i.Sensitive,
		&i.ArchivedAt,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateMemoryRecord = `-- name: UpdateCandidateMemoryRecord :one
UPDATE candidate_memory_records
SET memory_type = $2,
    title = $3,
    body = $4,
    source = $5,
    approved = $6,
    sensitive = $7,
    metadata = $8,
    updated_at = $9
WHERE id = $1
RETURNING id, memory_type, title, body, source, approved, sensitive,
          archived_at, superseded_by, metadata, created_at, updated_at
`

type UpdateCandidateMemoryRecordParams struct {
	ID         string
	MemoryType string
	Title      string
	Body       string
	Source     string
	Approved   bool
	Sensitive  bool
	Metadata   json.RawMessage
	UpdatedAt  time.Time
}

func (q *Queries) UpdateCandidateMemoryRecord(ctx context.Context, arg UpdateCandidateMemoryRecordParams) (CandidateMemoryRecord, error) {
	row := q.db.QueryRowContext(ctx, updateCandidateMemoryRecord,
		arg.ID,
		arg.MemoryType,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Approved,
		arg.Sensitive,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i CandidateMemoryRecord
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Approved,
		&i.Sensitive,
		&i.ArchivedAt,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
