// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidate_profiles.sql

package db

import (
	"context"
	"time"
)

const getCandidateProfile = `-- name: GetCandidateProfile :one
SELECT id, target_roles, preferred_stack, compensation_expectations, location_preferences,
       work_constraints, company_preferences, writing_tone, positioning_summary,
       created_at, updated_at
FROM candidate_profiles
WHERE id = $1
`

func (q *Queries) GetCandidateProfile(ctx context.Context, id string) (CandidateProfile, error) {
	row := q.db.QueryRowContext(ctx, getCandidateProfile, id)
	var i CandidateProfile
	err := row.Scan(
		&i.ID,
		&i.TargetRoles,
		&i.PreferredStack,
		&i.CompensationExpectations,
		&i.LocationPreferences,
		&i.WorkConstraints,
		&i.CompanyPreferences,
		&i.WritingTone,
		&i.PositioningSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCandidateProfile = `-- name: UpsertCandidateProfile :one
INSERT INTO candidate_profiles (
    id, target_roles, preferred_stack, compensation_expectations, location_preferences,
    work_constraints, company_preferences, writing_tone, positioning_summary,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    target_roles = EXCLUDED.target_roles,
    preferred_stack = EXCLUDED.preferred_stack,
    compensation_expectations = EXCLUDED.compensation_expectations,
    location_preferences = EXCLUDED.location_preferences,
    work_constraints = EXCLUDED.work_constraints,
    company_preferences = EXCLUDED.company_preferences,
    writing_tone = EXCLUDED.writing_tone,
    positioning_summary = EXCLUDED.positioning_summary,
    updated_at = EXCLUDED.updated_at
RETURNING id, target_roles, preferred_stack, compensation_expectations, location_preferences,
          work_constraints, company_preferences, writing_tone, positioning_summary,
          created_at, updated_at
`

type UpsertCandidateProfileParams struct {
	ID                       string
	TargetRoles              string
	PreferredStack           string
	CompensationExpectations string
	LocationPreferences      string
	WorkConstraints          string
	CompanyPreferences       string
	WritingTone              string
	PositioningSummary       string
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) UpsertCandidateProfile(ctx context.Context, arg UpsertCandidateProfileParams) (CandidateProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertCandidateProfile,
		arg.ID,
		arg.TargetRoles,
		arg.PreferredStack,
		arg.CompensationExpectations,
		arg.LocationPreferences,
		arg.WorkConstraints,
		arg.CompanyPreferences,
		arg.WritingTone,
		arg.PositioningSummary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CandidateProfile
	err := row.Scan(
		&i.ID,
		&i.TargetRoles,
		&i.PreferredStack,
		&i.CompensationExpectations,
		&i.LocationPreferences,
		&i.WorkConstraints,
		&i.CompanyPreferences,
		&i.WritingTone,
		&i.PositioningSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
