// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow_ups.sql

package db

import (
	"context"
	"time"
)

const deactivateFollowUpsByApplication = `-- name: DeactivateFollowUpsByApplication :exec
UPDATE follow_up_reminders SET completed_at = $1 WHERE application_id = $2 AND completed_at IS NULL
`

type DeactivateFollowUpsByApplicationParams struct {
	CompletedAt   *time.Time
	ApplicationID string
}

func (q *Queries) DeactivateFollowUpsByApplication(ctx context.Context, arg DeactivateFollowUpsByApplicationParams) error {
	_, err := q.db.ExecContext(ctx, deactivateFollowUpsByApplication, arg.CompletedAt, arg.ApplicationID)
	return err
}

const getFollowUpByID = `-- name: GetFollowUpByID :one
SELECT id, application_id, due_at, note, completed_at FROM follow_up_reminders WHERE id = $1
`

type GetFollowUpByIDRow struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
}

func (q *Queries) GetFollowUpByID(ctx context.Context, id string) (GetFollowUpByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFollowUpByID, id)
	var i GetFollowUpByIDRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DueAt,
		&i.Note,
		&i.CompletedAt,
	)
	return i, err
}

const insertFollowUp = `-- name: InsertFollowUp :exec
INSERT INTO follow_up_reminders (id, application_id, due_at, note, completed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFollowUpParams struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
	CreatedAt     time.Time
}

func (q *Queries) InsertFollowUp(ctx context.Context, arg InsertFollowUpParams) error {
	_, err := q.db.ExecContext(ctx, insertFollowUp,
		arg.ID,
		arg.ApplicationID,
		arg.DueAt,
		arg.Note,
		arg.CompletedAt,
		arg.CreatedAt,
	)
	return err
}

const listFollowUpsByApplication = `-- name: ListFollowUpsByApplication :many
SELECT id, application_id, due_at, note, completed_at FROM follow_up_reminders WHERE application_id = $1 ORDER BY due_at ASC
`

type ListFollowUpsByApplicationRow struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
}

func (q *Queries) ListFollowUpsByApplication(ctx context.Context, applicationID string) ([]ListFollowUpsByApplicationRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowUpsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowUpsByApplicationRow
	for rows.Next() {
		var i ListFollowUpsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DueAt,
			&i.Note,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueFollowUps = `-- name: ListOverdueFollowUps :many
SELECT id, application_id, due_at, note, completed_at FROM follow_up_reminders WHERE completed_at IS NULL AND due_at < $1 ORDER BY due_at ASC
`

type ListOverdueFollowUpsRow struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
}

func (q *Queries) ListOverdueFollowUps(ctx context.Context, dueAt time.Time) ([]ListOverdueFollowUpsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueFollowUps, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueFollowUpsRow
	for rows.Next() {
		var i ListOverdueFollowUpsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DueAt,
			&i.Note,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingFollowUps = `-- name: ListUpcomingFollowUps :many
SELECT id, application_id, due_at, note, completed_at FROM follow_up_reminders WHERE completed_at IS NULL AND due_at > $1 ORDER BY due_at ASC
`

type ListUpcomingFollowUpsRow struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
}

func (q *Queries) ListUpcomingFollowUps(ctx context.Context, dueAt time.Time) ([]ListUpcomingFollowUpsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingFollowUps, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingFollowUpsRow
	for rows.Next() {
		var i ListUpcomingFollowUpsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DueAt,
			&i.Note,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFollowUpCompleted = `-- name: UpdateFollowUpCompleted :exec
UPDATE follow_up_reminders SET completed_at = $1 WHERE id = $2
`

type UpdateFollowUpCompletedParams struct {
	CompletedAt *time.Time
	ID          string
}

func (q *Queries) UpdateFollowUpCompleted(ctx context.Context, arg UpdateFollowUpCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateFollowUpCompleted, arg.CompletedAt, arg.ID)
	return err
}
