// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interviews.sql

package db

import (
	"context"
	"time"
)

const getInterviewByID = `-- name: GetInterviewByID :one
SELECT id, type, scheduled_at, notes, outcome FROM interviews WHERE id = $1
`

type GetInterviewByIDRow struct {
	ID          string
	Type        string
	ScheduledAt time.Time
	Notes       string
	Outcome     string
}

func (q *Queries) GetInterviewByID(ctx context.Context, id string) (GetInterviewByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getInterviewByID, id)
	var i GetInterviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ScheduledAt,
		&i.Notes,
		&i.Outcome,
	)
	return i, err
}

const insertInterview = `-- name: InsertInterview :exec
INSERT INTO interviews (id, application_id, type, scheduled_at, notes, outcome, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertInterviewParams struct {
	ID            string
	ApplicationID string
	Type          string
	ScheduledAt   time.Time
	Notes         string
	Outcome       string
	CreatedAt     time.Time
}

func (q *Queries) InsertInterview(ctx context.Context, arg InsertInterviewParams) error {
	_, err := q.db.ExecContext(ctx, insertInterview,
		arg.ID,
		arg.ApplicationID,
		arg.Type,
		arg.ScheduledAt,
		arg.Notes,
		arg.Outcome,
		arg.CreatedAt,
	)
	return err
}

const listInterviewsByApplication = `-- name: ListInterviewsByApplication :many
SELECT id, type, scheduled_at, notes, outcome FROM interviews WHERE application_id = $1 ORDER BY scheduled_at ASC
`

type ListInterviewsByApplicationRow struct {
	ID          string
	Type        string
	ScheduledAt time.Time
	Notes       string
	Outcome     string
}

func (q *Queries) ListInterviewsByApplication(ctx context.Context, applicationID string) ([]ListInterviewsByApplicationRow, error) {
	rows, err := q.db.QueryContext(ctx, listInterviewsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInterviewsByApplicationRow
	for rows.Next() {
		var i ListInterviewsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ScheduledAt,
			&i.Notes,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewOutcome = `-- name: UpdateInterviewOutcome :exec
UPDATE interviews SET outcome = $1 WHERE id = $2
`

type UpdateInterviewOutcomeParams struct {
	Outcome string
	ID      string
}

func (q *Queries) UpdateInterviewOutcome(ctx context.Context, arg UpdateInterviewOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, updateInterviewOutcome, arg.Outcome, arg.ID)
	return err
}
