// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_applications.sql

package db

import (
	"context"
	"time"
)

const getJobApplicationByID = `-- name: GetJobApplicationByID :one
SELECT id, company, role_title, posting_url, source, location, compensation, employment_type, stage, created_at
FROM job_applications WHERE id = $1
`

func (q *Queries) GetJobApplicationByID(ctx context.Context, id string) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, getJobApplicationByID, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.RoleTitle,
		&i.PostingUrl,
		&i.Source,
		&i.Location,
		&i.Compensation,
		&i.EmploymentType,
		&i.Stage,
		&i.CreatedAt,
	)
	return i, err
}

const insertJobApplication = `-- name: InsertJobApplication :exec
INSERT INTO job_applications (id, company, role_title, posting_url, source, location, compensation, employment_type, stage, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertJobApplicationParams struct {
	ID             string
	Company        string
	RoleTitle      string
	PostingUrl     string
	Source         string
	Location       string
	Compensation   string
	EmploymentType string
	Stage          string
	CreatedAt      time.Time
}

func (q *Queries) InsertJobApplication(ctx context.Context, arg InsertJobApplicationParams) error {
	_, err := q.db.ExecContext(ctx, insertJobApplication,
		arg.ID,
		arg.Company,
		arg.RoleTitle,
		arg.PostingUrl,
		arg.Source,
		arg.Location,
		arg.Compensation,
		arg.EmploymentType,
		arg.Stage,
		arg.CreatedAt,
	)
	return err
}

const listJobApplications = `-- name: ListJobApplications :many
SELECT id, company, role_title, posting_url, source, location, compensation, employment_type, stage, created_at
FROM job_applications
ORDER BY created_at ASC
`

func (q *Queries) ListJobApplications(ctx context.Context) ([]JobApplication, error) {
	rows, err := q.db.QueryContext(ctx, listJobApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.RoleTitle,
			&i.PostingUrl,
			&i.Source,
			&i.Location,
			&i.Compensation,
			&i.EmploymentType,
			&i.Stage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobApplicationStage = `-- name: UpdateJobApplicationStage :exec
UPDATE job_applications SET stage = $1 WHERE id = $2
`

type UpdateJobApplicationStageParams struct {
	Stage string
	ID    string
}

func (q *Queries) UpdateJobApplicationStage(ctx context.Context, arg UpdateJobApplicationStageParams) error {
	_, err := q.db.ExecContext(ctx, updateJobApplicationStage, arg.Stage, arg.ID)
	return err
}
