// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AiArtifact struct {
	ID                string
	ArtifactType      string
	OwnerType         string
	OwnerID           string
	Title             string
	SourceInputs      json.RawMessage
	GeneratedContent  string
	UserEditedContent sql.NullString
	Status            string
	Sensitive         bool
	SupersededBy      sql.NullString
	ProviderName      sql.NullString
	ModelName         sql.NullString
	PromptID          sql.NullString
	UsageMetadata     json.RawMessage
	RawProviderID     sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ApplicationNote struct {
	ID            string
	ApplicationID string
	Body          string
	CreatedAt     time.Time
}

type CandidateMemoryRecord struct {
	ID           string
	MemoryType   string
	Title        string
	Body         string
	Source       string
	Approved     bool
	Sensitive    bool
	ArchivedAt   *time.Time
	SupersededBy sql.NullString
	Metadata     json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CandidateProfile struct {
	ID                       string
	TargetRoles              string
	PreferredStack           string
	CompensationExpectations string
	LocationPreferences      string
	WorkConstraints          string
	CompanyPreferences       string
	WritingTone              string
	PositioningSummary       string
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type FollowUpReminder struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
	CreatedAt     time.Time
}

type Interview struct {
	ID            string
	ApplicationID string
	Type          string
	ScheduledAt   time.Time
	Notes         string
	Outcome       string
	CreatedAt     time.Time
}

type JobApplication struct {
	ID             string
	Company        string
	RoleTitle      string
	PostingUrl     string
	Source         string
	Location       string
	Compensation   string
	EmploymentType string
	Stage          string
	CreatedAt      time.Time
}

type RoleRecord struct {
	ID                    string
	SearchTopicID         sql.NullString
	Company               string
	Title                 string
	PostingUrl            string
	Source                string
	SourceKind            string
	ProviderSource        string
	Description           string
	RawSourceText         string
	Location              string
	RemoteEligibility     string
	EmploymentType        string
	Seniority             string
	Compensation          string
	Stack                 string
	CompanyType           string
	FreshnessStatus       string
	FreshnessCheckedAt    *time.Time
	DecisionStatus        string
	RejectionReason       string
	PromotedApplicationID sql.NullString
	Metadata              json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type RoleSearchTopic struct {
	ID               string
	Name             string
	TargetTitles     string
	PreferredStack   string
	Location         string
	RemotePreference string
	EmploymentType   string
	CompanyType      string
	Compensation     string
	Seniority        string
	Notes            string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type TimelineEvent struct {
	ID            string
	ApplicationID string
	Description   string
	OccurredAt    time.Time
}
