// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ApplicationNote struct {
	ID            string
	ApplicationID string
	Body          string
	CreatedAt     time.Time
}

type FollowUpReminder struct {
	ID            string
	ApplicationID string
	DueAt         time.Time
	Note          string
	CompletedAt   *time.Time
	CreatedAt     time.Time
}

type Interview struct {
	ID            string
	ApplicationID string
	Type          string
	ScheduledAt   time.Time
	Notes         string
	Outcome       string
	CreatedAt     time.Time
}

type JobApplication struct {
	ID             string
	Company        string
	RoleTitle      string
	PostingUrl     string
	Source         string
	Location       string
	Compensation   string
	EmploymentType string
	Stage          string
	CreatedAt      time.Time
}

type TimelineEvent struct {
	ID            string
	ApplicationID string
	Description   string
	OccurredAt    time.Time
}
