// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
	"time"
)

const insertApplicationNote = `-- name: InsertApplicationNote :exec
INSERT INTO application_notes (id, application_id, body, created_at) VALUES ($1, $2, $3, $4)
`

type InsertApplicationNoteParams struct {
	ID            string
	ApplicationID string
	Body          string
	CreatedAt     time.Time
}

func (q *Queries) InsertApplicationNote(ctx context.Context, arg InsertApplicationNoteParams) error {
	_, err := q.db.ExecContext(ctx, insertApplicationNote,
		arg.ID,
		arg.ApplicationID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const listApplicationNotesByApplication = `-- name: ListApplicationNotesByApplication :many
SELECT id, body, created_at FROM application_notes WHERE application_id = $1 ORDER BY created_at ASC
`

type ListApplicationNotesByApplicationRow struct {
	ID        string
	Body      string
	CreatedAt time.Time
}

func (q *Queries) ListApplicationNotesByApplication(ctx context.Context, applicationID string) ([]ListApplicationNotesByApplicationRow, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationNotesByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationNotesByApplicationRow
	for rows.Next() {
		var i ListApplicationNotesByApplicationRow
		if err := rows.Scan(&i.ID, &i.Body, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
