// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_search_topics.sql

package db

import (
	"context"
	"time"
)

const getRoleSearchTopic = `-- name: GetRoleSearchTopic :one
SELECT id, name, target_titles, preferred_stack, location, remote_preference, employment_type, company_type, compensation, seniority, notes, created_at, updated_at FROM role_search_topics
WHERE id = $1
`

func (q *Queries) GetRoleSearchTopic(ctx context.Context, id string) (RoleSearchTopic, error) {
	row := q.db.QueryRowContext(ctx, getRoleSearchTopic, id)
	var i RoleSearchTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetTitles,
		&i.PreferredStack,
		&i.Location,
		&i.RemotePreference,
		&i.EmploymentType,
		&i.CompanyType,
		&i.Compensation,
		&i.Seniority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoleSearchTopic = `-- name: InsertRoleSearchTopic :one
INSERT INTO role_search_topics (
    id, name, target_titles, preferred_stack, location, remote_preference,
    employment_type, company_type, compensation, seniority, notes, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, name, target_titles, preferred_stack, location, remote_preference, employment_type, company_type, compensation, seniority, notes, created_at, updated_at
`

type InsertRoleSearchTopicParams struct {
	ID               string
	Name             string
	TargetTitles     string
	PreferredStack   string
	Location         string
	RemotePreference string
	EmploymentType   string
	CompanyType      string
	Compensation     string
	Seniority        string
	Notes            string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertRoleSearchTopic(ctx context.Context, arg InsertRoleSearchTopicParams) (RoleSearchTopic, error) {
	row := q.db.QueryRowContext(ctx, insertRoleSearchTopic,
		arg.ID,
		arg.Name,
		arg.TargetTitles,
		arg.PreferredStack,
		arg.Location,
		arg.RemotePreference,
		arg.EmploymentType,
		arg.CompanyType,
		arg.Compensation,
		arg.Seniority,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RoleSearchTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetTitles,
		&i.PreferredStack,
		&i.Location,
		&i.RemotePreference,
		&i.EmploymentType,
		&i.CompanyType,
		&i.Compensation,
		&i.Seniority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoleSearchTopics = `-- name: ListRoleSearchTopics :many
SELECT id, name, target_titles, preferred_stack, location, remote_preference, employment_type, company_type, compensation, seniority, notes, created_at, updated_at FROM role_search_topics
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListRoleSearchTopics(ctx context.Context) ([]RoleSearchTopic, error) {
	rows, err := q.db.QueryContext(ctx, listRoleSearchTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleSearchTopic
	for rows.Next() {
		var i RoleSearchTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetTitles,
			&i.PreferredStack,
			&i.Location,
			&i.RemotePreference,
			&i.EmploymentType,
			&i.CompanyType,
			&i.Compensation,
			&i.Seniority,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleSearchTopic = `-- name: UpdateRoleSearchTopic :one
UPDATE role_search_topics
SET name = $2,
    target_titles = $3,
    preferred_stack = $4,
    location = $5,
    remote_preference = $6,
    employment_type = $7,
    company_type = $8,
    compensation = $9,
    seniority = $10,
    notes = $11,
    updated_at = $12
WHERE id = $1
RETURNING id, name, target_titles, preferred_stack, location, remote_preference, employment_type, company_type, compensation, seniority, notes, created_at, updated_at
`

type UpdateRoleSearchTopicParams struct {
	ID               string
	Name             string
	TargetTitles     string
	PreferredStack   string
	Location         string
	RemotePreference string
	EmploymentType   string
	CompanyType      string
	Compensation     string
	Seniority        string
	Notes            string
	UpdatedAt        time.Time
}

func (q *Queries) UpdateRoleSearchTopic(ctx context.Context, arg UpdateRoleSearchTopicParams) (RoleSearchTopic, error) {
	row := q.db.QueryRowContext(ctx, updateRoleSearchTopic,
		arg.ID,
		arg.Name,
		arg.TargetTitles,
		arg.PreferredStack,
		arg.Location,
		arg.RemotePreference,
		arg.EmploymentType,
		arg.CompanyType,
		arg.Compensation,
		arg.Seniority,
		arg.Notes,
		arg.UpdatedAt,
	)
	var i RoleSearchTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetTitles,
		&i.PreferredStack,
		&i.Location,
		&i.RemotePreference,
		&i.EmploymentType,
		&i.CompanyType,
		&i.Compensation,
		&i.Seniority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
