// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_records.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const findActiveRoleRecordByPostingURL = `-- name: FindActiveRoleRecordByPostingURL :one
SELECT id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at FROM role_records
WHERE posting_url = $1
  AND posting_url <> ''
  AND decision_status <> 'Rejected'
LIMIT 1
`

func (q *Queries) FindActiveRoleRecordByPostingURL(ctx context.Context, postingUrl string) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, findActiveRoleRecordByPostingURL, postingUrl)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleRecord = `-- name: GetRoleRecord :one
SELECT id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at FROM role_records
WHERE id = $1
`

func (q *Queries) GetRoleRecord(ctx context.Context, id string) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, getRoleRecord, id)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoleRecord = `-- name: InsertRoleRecord :one
INSERT INTO role_records (
    id, search_topic_id, company, title, posting_url, source, source_kind,
    provider_source, description, raw_source_text, location, remote_eligibility,
    employment_type, seniority, compensation, stack, company_type, freshness_status,
    freshness_checked_at, decision_status, rejection_reason, promoted_application_id,
    metadata, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22,
    $23, $24, $25
)
RETURNING id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at
`

type InsertRoleRecordParams struct {
	ID                    string
	SearchTopicID         sql.NullString
	Company               string
	Title                 string
	PostingUrl            string
	Source                string
	SourceKind            string
	ProviderSource        string
	Description           string
	RawSourceText         string
	Location              string
	RemoteEligibility     string
	EmploymentType        string
	Seniority             string
	Compensation          string
	Stack                 string
	CompanyType           string
	FreshnessStatus       string
	FreshnessCheckedAt    *time.Time
	DecisionStatus        string
	RejectionReason       string
	PromotedApplicationID sql.NullString
	Metadata              json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) InsertRoleRecord(ctx context.Context, arg InsertRoleRecordParams) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, insertRoleRecord,
		arg.ID,
		arg.SearchTopicID,
		arg.Company,
		arg.Title,
		arg.PostingUrl,
		arg.Source,
		arg.SourceKind,
		arg.ProviderSource,
		arg.Description,
		arg.RawSourceText,
		arg.Location,
		arg.RemoteEligibility,
		arg.EmploymentType,
		arg.Seniority,
		arg.Compensation,
		arg.Stack,
		arg.CompanyType,
		arg.FreshnessStatus,
		arg.FreshnessCheckedAt,
		arg.DecisionStatus,
		arg.RejectionReason,
		arg.PromotedApplicationID,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkRoleRecordPromotedApplication = `-- name: LinkRoleRecordPromotedApplication :one
UPDATE role_records
SET decision_status = 'Promoted',
    promoted_application_id = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at
`

type LinkRoleRecordPromotedApplicationParams struct {
	ID                    string
	PromotedApplicationID sql.NullString
	UpdatedAt             time.Time
}

func (q *Queries) LinkRoleRecordPromotedApplication(ctx context.Context, arg LinkRoleRecordPromotedApplicationParams) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, linkRoleRecordPromotedApplication, arg.ID, arg.PromotedApplicationID, arg.UpdatedAt)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoleRecords = `-- name: ListRoleRecords :many
SELECT id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at FROM role_records
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListRoleRecords(ctx context.Context) ([]RoleRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRoleRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleRecord
	for rows.Next() {
		var i RoleRecord
		if err := rows.Scan(
			&i.ID,
			&i.SearchTopicID,
			&i.Company,
			&i.Title,
			&i.PostingUrl,
			&i.Source,
			&i.SourceKind,
			&i.ProviderSource,
			&i.Description,
			&i.RawSourceText,
			&i.Location,
			&i.RemoteEligibility,
			&i.EmploymentType,
			&i.Seniority,
			&i.Compensation,
			&i.Stack,
			&i.CompanyType,
			&i.FreshnessStatus,
			&i.FreshnessCheckedAt,
			&i.DecisionStatus,
			&i.RejectionReason,
			&i.PromotedApplicationID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleRecord = `-- name: UpdateRoleRecord :one
UPDATE role_records
SET company = $2,
    title = $3,
    posting_url = $4,
    source = $5,
    source_kind = $6,
    provider_source = $7,
    description = $8,
    location = $9,
    remote_eligibility = $10,
    employment_type = $11,
    seniority = $12,
    compensation = $13,
    stack = $14,
    company_type = $15,
    metadata = $16,
    updated_at = $17
WHERE id = $1
RETURNING id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at
`

type UpdateRoleRecordParams struct {
	ID                string
	Company           string
	Title             string
	PostingUrl        string
	Source            string
	SourceKind        string
	ProviderSource    string
	Description       string
	Location          string
	RemoteEligibility string
	EmploymentType    string
	Seniority         string
	Compensation      string
	Stack             string
	CompanyType       string
	Metadata          json.RawMessage
	UpdatedAt         time.Time
}

func (q *Queries) UpdateRoleRecord(ctx context.Context, arg UpdateRoleRecordParams) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, updateRoleRecord,
		arg.ID,
		arg.Company,
		arg.Title,
		arg.PostingUrl,
		arg.Source,
		arg.SourceKind,
		arg.ProviderSource,
		arg.Description,
		arg.Location,
		arg.RemoteEligibility,
		arg.EmploymentType,
		arg.Seniority,
		arg.Compensation,
		arg.Stack,
		arg.CompanyType,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoleRecordDecision = `-- name: UpdateRoleRecordDecision :one
UPDATE role_records
SET decision_status = $2,
    rejection_reason = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at
`

type UpdateRoleRecordDecisionParams struct {
	ID              string
	DecisionStatus  string
	RejectionReason string
	UpdatedAt       time.Time
}

func (q *Queries) UpdateRoleRecordDecision(ctx context.Context, arg UpdateRoleRecordDecisionParams) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, updateRoleRecordDecision,
		arg.ID,
		arg.DecisionStatus,
		arg.RejectionReason,
		arg.UpdatedAt,
	)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoleRecordFreshness = `-- name: UpdateRoleRecordFreshness :one
UPDATE role_records
SET freshness_status = $2,
    freshness_checked_at = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, search_topic_id, company, title, posting_url, source, source_kind, provider_source, description, raw_source_text, location, remote_eligibility, employment_type, seniority, compensation, stack, company_type, freshness_status, freshness_checked_at, decision_status, rejection_reason, promoted_application_id, metadata, created_at, updated_at
`

type UpdateRoleRecordFreshnessParams struct {
	ID                 string
	FreshnessStatus    string
	FreshnessCheckedAt *time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpdateRoleRecordFreshness(ctx context.Context, arg UpdateRoleRecordFreshnessParams) (RoleRecord, error) {
	row := q.db.QueryRowContext(ctx, updateRoleRecordFreshness,
		arg.ID,
		arg.FreshnessStatus,
		arg.FreshnessCheckedAt,
		arg.UpdatedAt,
	)
	var i RoleRecord
	err := row.Scan(
		&i.ID,
		&i.SearchTopicID,
		&i.Company,
		&i.Title,
		&i.PostingUrl,
		&i.Source,
		&i.SourceKind,
		&i.ProviderSource,
		&i.Description,
		&i.RawSourceText,
		&i.Location,
		&i.RemoteEligibility,
		&i.EmploymentType,
		&i.Seniority,
		&i.Compensation,
		&i.Stack,
		&i.CompanyType,
		&i.FreshnessStatus,
		&i.FreshnessCheckedAt,
		&i.DecisionStatus,
		&i.RejectionReason,
		&i.PromotedApplicationID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
