// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline_events.sql

package db

import (
	"context"
	"time"
)

const insertTimelineEvent = `-- name: InsertTimelineEvent :exec
INSERT INTO timeline_events (id, application_id, description, occurred_at) VALUES ($1, $2, $3, $4)
`

type InsertTimelineEventParams struct {
	ID            string
	ApplicationID string
	Description   string
	OccurredAt    time.Time
}

func (q *Queries) InsertTimelineEvent(ctx context.Context, arg InsertTimelineEventParams) error {
	_, err := q.db.ExecContext(ctx, insertTimelineEvent,
		arg.ID,
		arg.ApplicationID,
		arg.Description,
		arg.OccurredAt,
	)
	return err
}

const listTimelineEventsByApplication = `-- name: ListTimelineEventsByApplication :many
SELECT id, description, occurred_at FROM timeline_events WHERE application_id = $1 ORDER BY occurred_at ASC
`

type ListTimelineEventsByApplicationRow struct {
	ID          string
	Description string
	OccurredAt  time.Time
}

func (q *Queries) ListTimelineEventsByApplication(ctx context.Context, applicationID string) ([]ListTimelineEventsByApplicationRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEventsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineEventsByApplicationRow
	for rows.Next() {
		var i ListTimelineEventsByApplicationRow
		if err := rows.Scan(&i.ID, &i.Description, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
