package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/tonirilix/react-hexagonal-architecture/apps/api/graph"
	"github.com/tonirilix/react-hexagonal-architecture/apps/api/graph/model"
	"github.com/tonirilix/react-hexagonal-architecture/apps/api/internal/application/ports"
	"github.com/tonirilix/react-hexagonal-architecture/apps/api/internal/application/usecases"
	"github.com/tonirilix/react-hexagonal-architecture/apps/api/internal/domain"
)

// CreateSavedOpportunity is the resolver for the createSavedOpportunity field.
func (r *mutationResolver) CreateSavedOpportunity(ctx context.Context, input model.CreateSavedOpportunityInput) (*model.JobApplication, error) {
	source, err := mapJobSourceInput(input.Source)
	if err != nil {
		return nil, err
	}
	employmentType, err := mapEmploymentTypeInput(input.EmploymentType)
	if err != nil {
		return nil, err
	}
	app, err := r.CreateApplicationUC.Execute(usecases.CreateApplicationCommand{
		Company:        input.Company,
		RoleTitle:      input.RoleTitle,
		PostingURL:     input.PostingURL,
		Source:         source,
		Location:       input.Location,
		Compensation:   input.Compensation,
		EmploymentType: employmentType,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// AdvanceApplicationStage is the resolver for the advanceApplicationStage field.
func (r *mutationResolver) AdvanceApplicationStage(ctx context.Context, input model.AdvanceApplicationStageInput) (*model.JobApplication, error) {
	toStage, err := mapApplicationStageInput(input.ToStage)
	if err != nil {
		return nil, err
	}
	app, err := r.AdvanceStageUC.Execute(usecases.AdvanceStageCommand{
		ApplicationID: input.ApplicationID,
		ToStage:       toStage,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// ScheduleInterview is the resolver for the scheduleInterview field.
func (r *mutationResolver) ScheduleInterview(ctx context.Context, input model.ScheduleInterviewInput) (*model.JobApplication, error) {
	interviewType, err := mapInterviewTypeInput(input.Type)
	if err != nil {
		return nil, err
	}
	outcome, err := mapInterviewOutcomeInput(input.Outcome)
	if err != nil {
		return nil, err
	}
	app, err := r.ScheduleInterviewUC.Execute(usecases.ScheduleInterviewCommand{
		ApplicationID: input.ApplicationID,
		Type:          interviewType,
		ScheduledAt:   input.ScheduledAt,
		Notes:         input.Notes,
		Outcome:       outcome,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// CreateFollowUpReminder is the resolver for the createFollowUpReminder field.
func (r *mutationResolver) CreateFollowUpReminder(ctx context.Context, input model.CreateFollowUpReminderInput) (*model.JobApplication, error) {
	app, err := r.AddFollowUpUC.Execute(usecases.CreateFollowUpCommand{
		ApplicationID: input.ApplicationID,
		DueAt:         input.DueAt,
		Note:          input.Note,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// CompleteFollowUpReminder is the resolver for the completeFollowUpReminder field.
func (r *mutationResolver) CompleteFollowUpReminder(ctx context.Context, input model.CompleteFollowUpReminderInput) (*model.JobApplication, error) {
	app, err := r.CompleteFollowUpUC.Execute(usecases.CompleteFollowUpCommand{
		ApplicationID: input.ApplicationID,
		ReminderID:    input.ReminderID,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// AddApplicationNote is the resolver for the addApplicationNote field.
func (r *mutationResolver) AddApplicationNote(ctx context.Context, input model.AddApplicationNoteInput) (*model.JobApplication, error) {
	app, err := r.AddNoteUC.Execute(usecases.AddNoteCommand{
		ApplicationID: input.ApplicationID,
		Body:          input.Body,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context) ([]*model.JobApplication, error) {
	apps, err := r.ListApplicationsUC.Execute(ports.ListApplicationsFilter{})
	if err != nil {
		return nil, err
	}
	out := make([]*model.JobApplication, len(apps))
	for i, app := range apps {
		out[i] = mapApplication(app)
	}
	return out, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func mapDomainError(err error) error {
	switch {
	case errors.Is(err, domain.ErrApplicationNotFound):
		return errors.New("application could not be found")
	case errors.Is(err, domain.ErrInvalidStageTransition):
		return errors.New("invalid stage transition")
	case errors.Is(err, domain.ErrCannotSchedule):
		return errors.New("interviews can only be scheduled after an opportunity has been applied to")
	case errors.Is(err, domain.ErrNoteBodyEmpty):
		return errors.New("note body must not be empty")
	case errors.Is(err, domain.ErrDueDateInPast):
		return errors.New("follow-up due date must be after the latest interaction")
	default:
		return err
	}
}
