package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/tonirilix/career-pipeline/apps/api/graph"
	"github.com/tonirilix/career-pipeline/apps/api/graph/model"
	"github.com/tonirilix/career-pipeline/apps/api/internal/application/ports"
	"github.com/tonirilix/career-pipeline/apps/api/internal/application/usecases"
	"github.com/tonirilix/career-pipeline/apps/api/internal/domain"
)

// CreateSavedOpportunity is the resolver for the createSavedOpportunity field.
func (r *mutationResolver) CreateSavedOpportunity(ctx context.Context, input model.CreateSavedOpportunityInput) (*model.JobApplication, error) {
	source, err := mapJobSourceInput(input.Source)
	if err != nil {
		return nil, err
	}
	employmentType, err := mapEmploymentTypeInput(input.EmploymentType)
	if err != nil {
		return nil, err
	}
	app, err := r.CreateApplicationUC.Execute(ctx, usecases.CreateApplicationCommand{
		Company:        input.Company,
		RoleTitle:      input.RoleTitle,
		PostingURL:     input.PostingURL,
		Source:         source,
		Location:       input.Location,
		Compensation:   input.Compensation,
		EmploymentType: employmentType,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// AdvanceApplicationStage is the resolver for the advanceApplicationStage field.
func (r *mutationResolver) AdvanceApplicationStage(ctx context.Context, input model.AdvanceApplicationStageInput) (*model.JobApplication, error) {
	toStage, err := mapApplicationStageInput(input.ToStage)
	if err != nil {
		return nil, err
	}
	app, err := r.AdvanceStageUC.Execute(ctx, usecases.AdvanceStageCommand{
		ApplicationID: input.ApplicationID,
		ToStage:       toStage,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// ScheduleInterview is the resolver for the scheduleInterview field.
func (r *mutationResolver) ScheduleInterview(ctx context.Context, input model.ScheduleInterviewInput) (*model.JobApplication, error) {
	interviewType, err := mapInterviewTypeInput(input.Type)
	if err != nil {
		return nil, err
	}
	app, err := r.ScheduleInterviewUC.Execute(ctx, usecases.ScheduleInterviewCommand{
		ApplicationID: input.ApplicationID,
		Type:          interviewType,
		ScheduledAt:   input.ScheduledAt,
		Notes:         input.Notes,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// RecordInterviewOutcome is the resolver for the recordInterviewOutcome field.
func (r *mutationResolver) RecordInterviewOutcome(ctx context.Context, input model.RecordInterviewOutcomeInput) (*model.JobApplication, error) {
	outcome, err := mapInterviewOutcomeInput(input.Outcome)
	if err != nil {
		return nil, err
	}
	app, err := r.RecordOutcomeUC.Execute(ctx, usecases.RecordInterviewOutcomeCommand{
		ApplicationID: input.ApplicationID,
		InterviewID:   input.InterviewID,
		Outcome:       outcome,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// CreateFollowUpReminder is the resolver for the createFollowUpReminder field.
func (r *mutationResolver) CreateFollowUpReminder(ctx context.Context, input model.CreateFollowUpReminderInput) (*model.JobApplication, error) {
	app, err := r.AddFollowUpUC.Execute(ctx, usecases.CreateFollowUpCommand{
		ApplicationID: input.ApplicationID,
		DueAt:         input.DueAt,
		Note:          input.Note,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// CompleteFollowUpReminder is the resolver for the completeFollowUpReminder field.
func (r *mutationResolver) CompleteFollowUpReminder(ctx context.Context, input model.CompleteFollowUpReminderInput) (*model.JobApplication, error) {
	app, err := r.CompleteFollowUpUC.Execute(ctx, usecases.CompleteFollowUpCommand{
		ApplicationID: input.ApplicationID,
		ReminderID:    input.ReminderID,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// AddApplicationNote is the resolver for the addApplicationNote field.
func (r *mutationResolver) AddApplicationNote(ctx context.Context, input model.AddApplicationNoteInput) (*model.JobApplication, error) {
	app, err := r.AddNoteUC.Execute(ctx, usecases.AddNoteCommand{
		ApplicationID: input.ApplicationID,
		Body:          input.Body,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapApplication(app), nil
}

// UpdateCandidateProfile is the resolver for the updateCandidateProfile field.
func (r *mutationResolver) UpdateCandidateProfile(ctx context.Context, input model.UpdateCandidateProfileInput) (*model.CandidateProfile, error) {
	profile, err := r.UpdateCandidateProfileUC.Execute(ctx, usecases.UpdateCandidateProfileCommand{
		TargetRoles:              input.TargetRoles,
		PreferredStack:           input.PreferredStack,
		CompensationExpectations: input.CompensationExpectations,
		LocationPreferences:      input.LocationPreferences,
		WorkConstraints:          input.WorkConstraints,
		CompanyPreferences:       input.CompanyPreferences,
		WritingTone:              input.WritingTone,
		PositioningSummary:       input.PositioningSummary,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateProfile(profile), nil
}

// CreateCandidateMemoryRecord is the resolver for the createCandidateMemoryRecord field.
func (r *mutationResolver) CreateCandidateMemoryRecord(ctx context.Context, input model.CreateCandidateMemoryRecordInput) (*model.CandidateMemoryRecord, error) {
	metadata, err := mapJSONInput(input.Metadata, `{}`)
	if err != nil {
		return nil, err
	}
	record, err := r.CandidateMemoryUC.Create(ctx, usecases.CreateMemoryRecordCommand{
		MemoryType: domain.MemoryType(input.MemoryType),
		Title:      input.Title,
		Body:       input.Body,
		Source:     input.Source,
		Approved:   input.Approved,
		Sensitive:  input.Sensitive,
		Metadata:   metadata,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateMemoryRecord(record), nil
}

// UpdateCandidateMemoryRecord is the resolver for the updateCandidateMemoryRecord field.
func (r *mutationResolver) UpdateCandidateMemoryRecord(ctx context.Context, input model.UpdateCandidateMemoryRecordInput) (*model.CandidateMemoryRecord, error) {
	metadata, err := mapJSONInput(input.Metadata, `{}`)
	if err != nil {
		return nil, err
	}
	record, err := r.CandidateMemoryUC.Update(ctx, usecases.UpdateMemoryRecordCommand{
		ID:         input.ID,
		MemoryType: domain.MemoryType(input.MemoryType),
		Title:      input.Title,
		Body:       input.Body,
		Source:     input.Source,
		Approved:   input.Approved,
		Sensitive:  input.Sensitive,
		Metadata:   metadata,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateMemoryRecord(record), nil
}

// ArchiveCandidateMemoryRecord is the resolver for the archiveCandidateMemoryRecord field.
func (r *mutationResolver) ArchiveCandidateMemoryRecord(ctx context.Context, id string) (*model.CandidateMemoryRecord, error) {
	record, err := r.CandidateMemoryUC.Archive(ctx, id)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateMemoryRecord(record), nil
}

// SupersedeCandidateMemoryRecord is the resolver for the supersedeCandidateMemoryRecord field.
func (r *mutationResolver) SupersedeCandidateMemoryRecord(ctx context.Context, id string, supersededBy string) (*model.CandidateMemoryRecord, error) {
	record, err := r.CandidateMemoryUC.Supersede(ctx, id, supersededBy)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateMemoryRecord(record), nil
}

// CreateAIArtifact is the resolver for the createAIArtifact field.
func (r *mutationResolver) CreateAIArtifact(ctx context.Context, input model.CreateAIArtifactInput) (*model.AIArtifact, error) {
	status, err := mapArtifactStatusInput(input.Status)
	if err != nil {
		return nil, mapDomainError(err)
	}
	sourceInputs, err := mapJSONInput(input.SourceInputs, `[]`)
	if err != nil {
		return nil, err
	}
	usageMetadata, err := mapJSONInput(input.UsageMetadata, `{}`)
	if err != nil {
		return nil, err
	}
	artifact, err := r.AIArtifactsUC.Create(ctx, usecases.CreateAIArtifactCommand{
		ArtifactType:      domain.ArtifactType(input.ArtifactType),
		Owner:             domain.OwnerReference{Type: input.OwnerType, ID: input.OwnerID},
		Title:             input.Title,
		SourceInputs:      sourceInputs,
		GeneratedContent:  input.GeneratedContent,
		UserEditedContent: input.UserEditedContent,
		Status:            status,
		Sensitive:         input.Sensitive,
		Provenance: domain.ArtifactProvenance{
			ProviderName:  input.ProviderName,
			ModelName:     input.ModelName,
			PromptID:      input.PromptID,
			UsageMetadata: usageMetadata,
			RawProviderID: input.RawProviderID,
		},
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapAIArtifact(artifact), nil
}

// EditAIArtifact is the resolver for the editAIArtifact field.
func (r *mutationResolver) EditAIArtifact(ctx context.Context, id string, userEditedContent *string) (*model.AIArtifact, error) {
	artifact, err := r.AIArtifactsUC.Edit(ctx, id, userEditedContent)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapAIArtifact(artifact), nil
}

// UpdateAIArtifactStatus is the resolver for the updateAIArtifactStatus field.
func (r *mutationResolver) UpdateAIArtifactStatus(ctx context.Context, id string, status string) (*model.AIArtifact, error) {
	mappedStatus, err := mapArtifactStatusInput(status)
	if err != nil {
		return nil, mapDomainError(err)
	}
	artifact, err := r.AIArtifactsUC.UpdateStatus(ctx, id, mappedStatus)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapAIArtifact(artifact), nil
}

// SupersedeAIArtifact is the resolver for the supersedeAIArtifact field.
func (r *mutationResolver) SupersedeAIArtifact(ctx context.Context, id string, supersededBy string) (*model.AIArtifact, error) {
	artifact, err := r.AIArtifactsUC.Supersede(ctx, id, supersededBy)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapAIArtifact(artifact), nil
}

// CreateRoleSearchTopic is the resolver for the createRoleSearchTopic field.
func (r *mutationResolver) CreateRoleSearchTopic(ctx context.Context, input model.UpsertRoleSearchTopicInput) (*model.RoleSearchTopic, error) {
	topic, err := r.RoleSearchTopicsUC.Create(ctx, roleSearchTopicCommandFromInput(input))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleSearchTopic(topic), nil
}

// UpdateRoleSearchTopic is the resolver for the updateRoleSearchTopic field.
func (r *mutationResolver) UpdateRoleSearchTopic(ctx context.Context, input model.UpsertRoleSearchTopicInput) (*model.RoleSearchTopic, error) {
	topic, err := r.RoleSearchTopicsUC.Update(ctx, roleSearchTopicCommandFromInput(input))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleSearchTopic(topic), nil
}

// RunRoleSearch is the resolver for the runRoleSearch field.
func (r *mutationResolver) RunRoleSearch(ctx context.Context, topicID string, maxRoles *int) (*model.RoleSearchRunResult, error) {
	limit := 0
	if maxRoles != nil {
		limit = *maxRoles
	}
	result, err := r.RoleRecordsUC.RunSearch(ctx, topicID, limit)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleSearchRunResult(result), nil
}

// CreateRoleFromURL is the resolver for the createRoleFromUrl field.
func (r *mutationResolver) CreateRoleFromURL(ctx context.Context, input model.RoleRecordInput) (*model.RoleRecord, error) {
	cmd, err := roleRecordCommandFromInput(input)
	if err != nil {
		return nil, err
	}
	role, err := r.RoleRecordsUC.CreateFromURL(ctx, cmd)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecord(role), nil
}

// CreateRoleFromPaste is the resolver for the createRoleFromPaste field.
func (r *mutationResolver) CreateRoleFromPaste(ctx context.Context, input model.RoleRecordInput) (*model.RoleRecord, error) {
	cmd, err := roleRecordCommandFromInput(input)
	if err != nil {
		return nil, err
	}
	role, err := r.RoleRecordsUC.CreateFromPaste(ctx, cmd)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecord(role), nil
}

// UpdateRoleRecord is the resolver for the updateRoleRecord field.
func (r *mutationResolver) UpdateRoleRecord(ctx context.Context, id string, input model.RoleRecordInput) (*model.RoleRecord, error) {
	cmd, err := roleRecordCommandFromInput(input)
	if err != nil {
		return nil, err
	}
	role, err := r.RoleRecordsUC.Update(ctx, id, cmd)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecord(role), nil
}

// UpdateRoleDecision is the resolver for the updateRoleDecision field.
func (r *mutationResolver) UpdateRoleDecision(ctx context.Context, id string, status string, rejectionReason *string) (*model.RoleRecord, error) {
	reason := domain.RoleRejectionNone
	if rejectionReason != nil {
		reason = domain.RoleRejectionReason(*rejectionReason)
	}
	role, err := r.RoleRecordsUC.UpdateDecision(ctx, usecases.UpdateRoleDecisionCommand{
		ID:              id,
		Status:          domain.RoleDecisionStatus(status),
		RejectionReason: reason,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecord(role), nil
}

// UpdateRoleFreshness is the resolver for the updateRoleFreshness field.
func (r *mutationResolver) UpdateRoleFreshness(ctx context.Context, id string, status string, checkedAt *string) (*model.RoleRecord, error) {
	var parsed *time.Time
	if checkedAt != nil && *checkedAt != "" {
		t, err := time.Parse(time.RFC3339, *checkedAt)
		if err != nil {
			return nil, err
		}
		parsed = &t
	}
	role, err := r.RoleRecordsUC.UpdateFreshness(ctx, usecases.UpdateRoleFreshnessCommand{
		ID:        id,
		Status:    domain.RoleFreshnessStatus(status),
		CheckedAt: parsed,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecord(role), nil
}

// PromoteRole is the resolver for the promoteRole field.
func (r *mutationResolver) PromoteRole(ctx context.Context, id string) (*model.PromoteRoleResult, error) {
	result, err := r.RoleRecordsUC.Promote(ctx, id)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.PromoteRoleResult{
		Role:        mapRoleRecord(result.Role),
		Application: mapApplication(result.Application),
	}, nil
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context) ([]*model.JobApplication, error) {
	apps, err := r.ListApplicationsUC.Execute(ctx, ports.ListApplicationsFilter{})
	if err != nil {
		return nil, err
	}
	out := make([]*model.JobApplication, len(apps))
	for i, app := range apps {
		out[i] = mapApplication(app)
	}
	return out, nil
}

// CandidateProfile is the resolver for the candidateProfile field.
func (r *queryResolver) CandidateProfile(ctx context.Context) (*model.CandidateProfile, error) {
	profile, err := r.GetCandidateProfileUC.Execute(ctx)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateProfile(profile), nil
}

// CandidateMemoryRecords is the resolver for the candidateMemoryRecords field.
func (r *queryResolver) CandidateMemoryRecords(ctx context.Context) ([]*model.CandidateMemoryRecord, error) {
	records, err := r.CandidateMemoryUC.List(ctx)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateMemoryRecords(records), nil
}

// CandidateGroundingContext is the resolver for the candidateGroundingContext field.
func (r *queryResolver) CandidateGroundingContext(ctx context.Context) (*model.CandidateGroundingContext, error) {
	grounding, err := r.GroundingContextUC.Execute(ctx)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapCandidateGroundingContext(grounding), nil
}

// AiArtifacts is the resolver for the aiArtifacts field.
func (r *queryResolver) AiArtifacts(ctx context.Context, ownerType string, ownerID string) ([]*model.AIArtifact, error) {
	artifacts, err := r.AIArtifactsUC.ListByOwner(ctx, domain.OwnerReference{Type: ownerType, ID: ownerID})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapAIArtifacts(artifacts), nil
}

// RoleSearchTopics is the resolver for the roleSearchTopics field.
func (r *queryResolver) RoleSearchTopics(ctx context.Context) ([]*model.RoleSearchTopic, error) {
	topics, err := r.RoleSearchTopicsUC.List(ctx)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleSearchTopics(topics), nil
}

// RoleRecords is the resolver for the roleRecords field.
func (r *queryResolver) RoleRecords(ctx context.Context, filter *model.RoleRecordsFilterInput) ([]*model.RoleRecord, error) {
	roles, err := r.RoleRecordsUC.List(ctx, roleRecordFilterFromInput(filter))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecords(roles), nil
}

// RoleRecord is the resolver for the roleRecord field.
func (r *queryResolver) RoleRecord(ctx context.Context, id string) (*model.RoleRecord, error) {
	role, err := r.RoleRecordsUC.Get(ctx, id)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapRoleRecord(role), nil
}

func roleSearchTopicCommandFromInput(input model.UpsertRoleSearchTopicInput) usecases.UpsertRoleSearchTopicCommand {
	id := ""
	if input.ID != nil {
		id = *input.ID
	}
	return usecases.UpsertRoleSearchTopicCommand{
		ID:               id,
		Name:             input.Name,
		TargetTitles:     input.TargetTitles,
		PreferredStack:   input.PreferredStack,
		Location:         input.Location,
		RemotePreference: input.RemotePreference,
		EmploymentType:   domain.EmploymentType(input.EmploymentType),
		CompanyType:      domain.RoleCompanyType(input.CompanyType),
		Compensation:     input.Compensation,
		Seniority:        domain.RoleSeniority(input.Seniority),
		Notes:            input.Notes,
	}
}

func roleRecordCommandFromInput(input model.RoleRecordInput) (usecases.RoleRecordCommand, error) {
	metadata, err := mapJSONInput(input.Metadata, `{}`)
	if err != nil {
		return usecases.RoleRecordCommand{}, err
	}
	sourceKind := domain.RoleSourceOther
	if input.SourceKind != nil {
		sourceKind = domain.RoleSourceKind(*input.SourceKind)
	}
	providerSource := ""
	if input.ProviderSource != nil {
		providerSource = *input.ProviderSource
	}
	rawSourceText := ""
	if input.RawSourceText != nil {
		rawSourceText = *input.RawSourceText
	}
	freshness := domain.RoleFreshnessUnknown
	if input.FreshnessStatus != nil {
		freshness = domain.RoleFreshnessStatus(*input.FreshnessStatus)
	}
	return usecases.RoleRecordCommand{
		SearchTopicID:     input.SearchTopicID,
		Company:           input.Company,
		Title:             input.Title,
		PostingURL:        input.PostingURL,
		Source:            input.Source,
		SourceKind:        sourceKind,
		ProviderSource:    providerSource,
		Description:       input.Description,
		RawSourceText:     rawSourceText,
		Location:          input.Location,
		RemoteEligibility: domain.RoleRemoteEligibility(input.RemoteEligibility),
		EmploymentType:    domain.EmploymentType(input.EmploymentType),
		Seniority:         domain.RoleSeniority(input.Seniority),
		Compensation:      input.Compensation,
		Stack:             input.Stack,
		CompanyType:       domain.RoleCompanyType(input.CompanyType),
		FreshnessStatus:   freshness,
		Metadata:          metadata,
	}, nil
}

func roleRecordFilterFromInput(input *model.RoleRecordsFilterInput) ports.ListRoleRecordsFilter {
	if input == nil {
		return ports.ListRoleRecordsFilter{}
	}
	filter := ports.ListRoleRecordsFilter{}
	if input.DecisionStatus != nil {
		status := domain.RoleDecisionStatus(*input.DecisionStatus)
		filter.DecisionStatus = &status
	}
	if input.FreshnessStatus != nil {
		status := domain.RoleFreshnessStatus(*input.FreshnessStatus)
		filter.FreshnessStatus = &status
	}
	if input.SourceKind != nil {
		sourceKind := domain.RoleSourceKind(*input.SourceKind)
		filter.SourceKind = &sourceKind
	}
	if input.SearchTerm != nil {
		filter.SearchTerm = *input.SearchTerm
	}
	return filter
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
